pullquote.settings:
  type: mapping
  label: Settings
  mapping:
    css:
      type: string
    scope:
      type: integer
    content_by_type:
      type: integer
    load_by_view_mode:
      type: integer
    view_modes:
      type: sequence
      sequence:
        type: string
    content_types:
      type: sequence
      sequence:
        type: string
    css_source:
      type: string
